// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DLQh4DwXwO2Lq_fxBlX3XLqG7K6eDIg',
    appId: '1:171162071360:web:3059afc7b186be8c7c8aa5',
    messagingSenderId: '171162071360',
    projectId: 'fit-x-4a83a',
    authDomain: 'fit-x-4a83a.firebaseapp.com',
    storageBucket: 'fit-x-4a83a.firebasestorage.app',
    measurementId: 'G-EB7ZEN19DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKhCmixbqgGUJTIbQ8PyEsVhh7Csei0c',
    appId: '1:171162071360:android:bb3a5e69f91389c47c8aa5',
    messagingSenderId: '171162071360',
    projectId: 'fit-x-4a83a',
    storageBucket: 'fit-x-4a83a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxheb5G3J5kLsCICm_0VbyNL2g0IgmumI',
    appId: '1:171162071360:ios:a1b85066cf99517e7c8aa5',
    messagingSenderId: '171162071360',
    projectId: 'fit-x-4a83a',
    storageBucket: 'fit-x-4a83a.firebasestorage.app',
    iosBundleId: 'com.example.fitx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxheb5G3J5kLsCICm_0VbyNL2g0IgmumI',
    appId: '1:171162071360:ios:a1b85066cf99517e7c8aa5',
    messagingSenderId: '171162071360',
    projectId: 'fit-x-4a83a',
    storageBucket: 'fit-x-4a83a.firebasestorage.app',
    iosBundleId: 'com.example.fitx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4DLQh4DwXwO2Lq_fxBlX3XLqG7K6eDIg',
    appId: '1:171162071360:web:bfc69b80c236ac7f7c8aa5',
    messagingSenderId: '171162071360',
    projectId: 'fit-x-4a83a',
    authDomain: 'fit-x-4a83a.firebaseapp.com',
    storageBucket: 'fit-x-4a83a.firebasestorage.app',
    measurementId: 'G-WGXJ09PG4M',
  );
}
